FROM node:18-alpine

RUN mkdir -p /srv/cf.errores

COPY ["package.json","/srv/cf.errores/"]

WORKDIR /srv/cf.errores

RUN npm install

COPY [".", "/srv/cf.errores/"]

EXPOSE $PORT

CMD [ "npm", "run", "dev" ]
