
x-common-variables: &common-variables
  NODE_ENV: "development"

services:

  mongodb_service:
    image: mongo
    container_name: mongodb_service
    volumes:
      - ../_mongodb:/data/db
    restart: always
  
  archivospublicos:
    build:
      context: ../cf.archivospublicos
      dockerfile: Dockerfile.dev
    image: archivospublicos:0.0.1
    container_name: archivospublicos
    depends_on:
      - mongodb_service
    volumes:
      - ../cf.archivospublicos:/srv/cf.archivospublicos/
      - /srv/cf.archivospublicos/node_modules
      - /srv/cf.archivospublicos/frontend/assets/lib/node_modules
    environment:
       <<: *common-variables
       PORT: ${PORT:-2201}
    ports:
      - "${PORT:-2201}:2201"
       
  account:
    build:
      context: ../cf.account
      dockerfile: Dockerfile.dev
    image: account:0.0.1
    container_name: account
    depends_on:
      - archivospublicos
    volumes:
      - ../cf.account:/srv/cf.account/
      - /srv/cf.account/node_modules
    environment:
       <<: *common-variables
       PORT: ${PORT:-2202}
    ports:
      - "${PORT:-2202}:2202"

  errores:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: errores:0.0.1
    container_name: errores
    depends_on:
      - account
    volumes:
      - .:/srv/cf.errores
      - /srv/cf.errores/node_modules
      - ./frontend/assets/:/srv/cf.errores/frontend/assets
    environment:
       <<: *common-variables
       PORT: ${PORT:-2299}
    ports:
      - "${PORT:-2299}:2299"