
services:
  
  errores:
    build:
      context: .
      dockerfile: Dockerfile
    image: errores:0.0.1
    container_name: errores
    volumes:
      - .:/srv/cf.errores
      - /srv/cf.errores/node_modules
      - ./frontend/assets/:/srv/cf.errores/frontend/assets
    environment:
       NODE_ENV: production
       PORT: ${PORT:-2299}
    ports:
      - "127.0.0.1:2299:2299"